### ISSUE TITLE
Some issues i've found on linux

### ISSUE THREAD

**Issue by Alex0007** [williamtguerra/white-ui#6]
![image](https://cloud.githubusercontent.com/assets/1143226/21447370/9cec8a5e-c8f5-11e6-82e0-c8015800b29f.png)

Hey, just found your theme. Looks nice, but here are some bugs I've found on Linux

- [ ] Strange indent guide styling
- [ ] Ugly webkit scrollbars
- [ ] Strange block on the left of code that can't be found in README screenshots

**Comment by williamtguerra** [comment]
> Strange indent guide styling

pretty sure thats your syntax

> Ugly webkit scrollbars

scrollbars are not modified with this theme

>  Strange block on the left of code that can't be found in README screenshots

pretty sure thats your linter  
that said, updates in the latest release clean up gutters a little

**Comment by guzgarcia** [comment]
@Alex0007 To fix the scrollbars just edit the webkit scrollbars. For example:

```less
::-webkit-scrollbar {
  height: .4375rem;
  width: .4375rem;
}

::-webkit-scrollbar-track {
  background-color: #eee;
  border-radius: .625rem;
}

::-webkit-scrollbar-thumb {
  border-radius: .625rem;
  background: #d9d9d9;
}
```

Here is how it looks:

![](https://i.imgur.com/TN8mWrO.png)
